name: Build and Deploy iOS App to TestFlight
on:
  push:
    branches:
      - your-new-branch-name  # Replace with your branch

jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.3'
          channel: stable
          architecture: x64

      - name: Install Flutter Dependencies
        run: |
          flutter pub get

      - name: Ensure iOS Setup
        env:
          FLUTTER_ROOT: /Users/runner/hostedtoolcache/flutter/stable-3.24.3-x64
        run: |
          if [ ! -d "ios" ] || [ ! -d ".ios" ]; then
            echo "iOS setup missing. Regenerating..."
            rm -rf ios .ios
            flutter create --platforms=ios --org com.atvandbuggy --project-name atvandbuggy_sales_app .
            flutter pub get
          fi
          cd ios
          # Overwrite Podfile with Flutter-compatible version
          cat << EOF > Podfile
          # Load Flutter's podhelper
          install! 'cocoapods', :deterministic_uuids => false
          platform :ios, '12.0'

          # Include Flutter podhelper
          flutter_root = File.expand_path(ENV['FLUTTER_ROOT'] || '$FLUTTER_ROOT')
          require File.join(flutter_root, 'packages', 'flutter_tools', 'bin', 'podhelper.rb')

          target 'Runner' do
            use_frameworks!
            use_modular_headers!
            flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
          end

          post_install do |installer|
            installer.pods_project.targets.each do |target|
              target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
              end
            end
          end
          EOF
          cat Podfile  # Print Podfile for debugging

      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods -v 1.15.2
          pod --version

      - name: Install Pods
        run: |
          cd ios
          pod install --repo-update

      - name: Setup App Store Connect API Key
        env:
          API_KEY_BASE64: ${{ secrets.API_KEY_BASE64 }}
        run: |
          echo "$API_KEY_BASE64" | base64 --decode > /tmp/authkey.p8
          if [ ! -s /tmp/authkey.p8 ]; then
            echo "Error: Decoded API key file is empty or invalid."
            exit 1
          fi
          echo "API key file created at /tmp/authkey.p8"

      - name: Debug Bundle ID and Signing
        run: |
          cd ios/Runner
          echo "Bundle ID in Info.plist:"
          plutil -p Info.plist | grep CFBundleIdentifier
          echo "Xcode project settings:"
          cat ../Runner.xcodeproj/project.pbxproj | grep -i "PRODUCT_BUNDLE_IDENTIFIER\|DEVELOPMENT_TEAM"

      - name: Build iOS App with Automatic Signing
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
          APPLE_ID: ${{ secrets.APPLE_ID }}
          APPLE_ID_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
          DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
        run: |
          cd ios
          # Set up keychain
          security create-keychain -p "temp" build.keychain
          security unlock-keychain -p "temp" build.keychain
          security set-keychain-settings -t 3600 build.keychain
          security default-keychain -s build.keychain

          # Authenticate and build
          echo "Authenticating with Apple ID..."
          xcrun xcodebuild -workspace Runner.xcworkspace \
            -scheme Runner \
            -sdk iphoneos \
            -configuration Release \
            -archivePath $GITHUB_WORKSPACE/build/Runner.xcarchive \
            clean archive \
            CODE_SIGN_STYLE="Automatic" \
            DEVELOPMENT_TEAM="$DEVELOPMENT_TEAM" \
            -allowProvisioningUpdates \
            -verbose

      - name: Export and Upload to TestFlight
        env:
          DEVELOPER_DIR: /Applications/Xcode_15.4.app/Contents/Developer
          API_ISSUER_ID: ${{ secrets.API_ISSUER_ID }}
          API_KEY_ID: ${{ secrets.API_KEY_ID }}
          DEVELOPMENT_TEAM: ${{ secrets.DEVELOPMENT_TEAM }}
        run: |
          cd ios
          cat << EOF > ExportOptions.plist
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$DEVELOPMENT_TEAM</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>destination</key>
              <string>upload</string>
          </dict>
          </plist>
          EOF

          # Export and upload to TestFlight
          xcrun xcodebuild -exportArchive \
            -archivePath $GITHUB_WORKSPACE/build/Runner.xcarchive \
            -exportOptionsPlist ExportOptions.plist \
            -exportPath $GITHUB_WORKSPACE/build \
            -allowProvisioningUpdates \
            -authenticationKeyPath /tmp/authkey.p8 \
            -authenticationKeyID "$API_KEY_ID" \
            -authenticationKeyIssuerID "$API_ISSUER_ID" \
            -verbose
